INHERIT: ../mkdocs.yml

markdown_extensions:
  toc:
    permalink: False
hooks:
- ../mkdocs-utils/hooks.py

# Override plugins to leave in only those that might matter.
plugins:
  - awesome-pages
  - meta-descriptions
